#cloud-config

users:  # Benutzerkonfiguration
  - name: ubuntu  # Name des Benutzers
    sudo: ALL=(ALL) NOPASSWD:ALL  # Ermöglicht dem Benutzer sudo-Rechte ohne Passwort
    groups: users, admin  # Gruppenmitgliedschaft des Benutzers
    home: /home/ubuntu  # Pfad zum Benutzerverzeichnis
    shell: /bin/bash  # Standard-Shell des Benutzers

    ssh_authorized_keys:  # Liste der zugelassenen SSH-Schlüssel
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCoNJnd3k8lkPVz7Ay95fOqN7R6+JBICvPPPHhlHYrgUsVvxpsYj5+FQZ+co63jts6/69FpZvmIQRB7cZXUyhyGJd4yptKAEbLosECl6nGslMypXeh5rex/VSmL89r3C7tL0aKWoAvCSBckrSiRjIRCPSYED8EPhIZMs1Ie5eMKgs+d19WtflTlkr6wzBW7gdxcKSL25JmByCrLJyBMcFnF0P/gcIZ74jdwyCdSFRB97u4GnofuM6KAdOAp5QuMLcu2VbbiRkZaRRps/dfIeLXWQHIvWsQNhol3AkH17ybcdEucJu+Gl5AMra/S43kqgPnepmAmTdipkUGeamIApI9b aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key-nussle


ssh_pwauth: false  # Deaktiviert das SSH-Passwort-Authentifizierungsverfahren
disable_root: false  # Erlaubt den Zugriff als Root-Benutzer
package_update: true  # Aktualisiert die Paketliste beim Start der VM

packages:  # Liste der zu installierenden Pakete
  - curl
  - wget
  - apache2
  - php
  - libapache2-mod-php

# Webserver neu starten
# In das Home-Verzeichnis wechseln
# Repository klonen
# PHP-Dateien in das Verzeichnis des Webservers kopieren
runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart apache2

# Datei für PHP-Dateien erstellen
write_files:
  - path: /var/www/html/db.php
    content: |
      <?php $ihrname = "Cameron Meile"; ?>
      <html>
      	<head>
      	<title><?php echo($ihrname) ?></title>
      	</head>
      	<body>
      		Es ist eine Hyäne auf jagd nach Frisch Fleisch von Afrika
      	<br />
      	<img src="https://kn04cameronmeile.s3.amazonaws.com/henrik-hansen-Xakezsdr1yk-unsplash.jpg" />

      	unsplash.com https://images.unsplash.com/photo-1608543104100-c24c77541d16?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
      	</body>
      </html>
